### ISSUE TITLE
README docs

### ISSUE THREAD

**Issue by model3volution** [aquent-it-solutions/reddit-humor#15]
Having seen a couple working demos of it the other day was great, I wanted to get more context on what the app does, but currently there isn't a readme.  This can make contributing difficult since there are no clear instructions on how to run/modify the application.

### Key points to outline
- [ ] Expected behavior of the app
- [ ] How to run the app
- [ ] Steps for contributing
- [ ] Todo list of ideas going forward

**Comment by ravi4theja** [comment]
We have the initial draft of the readme.md welcoming changes if necessary. Closing the issue for now.
